version: '3.8'

services:
  weather-readings-storage:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: weather-readings-storage
    ports:
      - "1436:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "G7f!pQx9#TzL@v3W"
    restart: unless-stopped

  jetstream:
    image: nats
    container_name: jetstream
    command: -js
    ports:
      - "4222:4222"
    restart: unless-stopped